### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by FezVrasta** [RollingVersions/RollingVersions#108]
Trying to open the page to add a changelog, it loads and after a while I get:

```
Something went wrong: : <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html>
```

URL:
https://rollingversions.com/popperjs/popper-core/pull/1139

**Comment by ForbesLindesay** [comment]
The error I get in the logs is "Could not resolve to a PullRequest with the number of 1". I'll investigate what's going on here and expect to have a fix for you by Wednesday evening.

**Comment by ForbesLindesay** [comment]
Scratch that, it turned out to be much easier to fix than I thought. It's up and working again now. Please let me know if you run into any other issues.

**Comment by FezVrasta** [comment]
Thanks!
