### ISSUE TITLE
We need a workaround for `npm owner ls` caching

### ISSUE THREAD

**Issue by ForbesLindesay** [RollingVersions/RollingVersions#116]
I've experienced this bug in npm: https://npm.community/t/the-npm-owner-add-command-is-not-doing-anything/5313

Unfortunately we use npm owner ls as a "precondition" on publishing, so this blocks publishing for some users

**Comment by scarlac** [comment]
It also happens while using the CLI. In fact, managing owners through the CLI is unreliable in total, even when reviewing via the web interface.

**Comment by ForbesLindesay** [comment]
I removed the pre-conditions checks on npm publishing because they created so many issues like this. We now just attempt to publish, which is less prone to these caching issues.
