### ISSUE TITLE
This build is not running against the latest commit in master.

### ISSUE THREAD

**Issue by FezVrasta** [RollingVersions/RollingVersions#156]
Hi, is there any way to disable the latest commit check on publish?

Right now if I try to publish from a commit different from master I get:

> GitHub pre-release steps failed:
>
>  This build is not running against the latest commit in master. To avoid awkward race conditions we'll skip publishing here and leave publishing to the other commit.

Thanks!

**Comment by ForbesLindesay** [comment]
There isn't currently, but I will add one. If it's that you want to publish from a different branch, it is also possible to pass the `--deploy-branch` flag to set the branch that should be used both for this check, and for searching for commits.

**Comment by FezVrasta** [comment]
We just need to deploy specific commits that have been validated by the QA team. If more commits are merged after the QA cycle we don't want to deploy untested changes.

**Comment by ForbesLindesay** [comment]
That makes sense. I'll release the new version as soon as it is tested, that should allow you to pass the flag to disable this check.

**Comment by ForbesLindesay** [comment]
That makes sense. I'll release the new version as soon as it is tested, that should allow you to pass the flag to disable this check.
